name: Lint & Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: '[test]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Download golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.23.6
        env:
          GO111MODULE: 'on'
      - name: Lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run --verbose
        env:
          GO111MODULE: 'on'
      - name: Install talib
        run: |
          sudo apt install build-essential wget -y
          wget https://downloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install
          sudo apt-get install libxml2-utils
          sudo pip install TA-Lib
      - name: test
        run: |
          make test_ci
        env:
          GO111MODULE: 'on'
